<div class="banner-image-video">
    <div class="banner-image-video__item">
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner-image-video-block-1')->toHtml();?>
    </div>
    <div class="banner-image-video__item">
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner-image-video-block-2')->toHtml();?>
    </div>
</div>