<div class="main-slide-banner">
    <div class="main-slide-banner__item">
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('slide-banner-block-1')->toHtml();?>
    </div>
    <div class="main-slide-banner__item">
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('slide-banner-block-2')->toHtml();?>
    </div>
</div>

<script type="text/javascript">
    require(['jquery', 'jquery/ui', 'slick'], function($) {
	    $(document).ready(function() {
	        $(".main-slide-banner").slick({
                dot: false,
	            infinite: true,
	            slidesToShow: 1,
                slidesToScroll: 1,
                arrows: false,
                swipeToSlide: true,
            });
        });
    })
</script>