<div class="banner-three-items">
    <div class="banner-three-items__item">
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner-three-items-block-1')->toHtml(); ?>
    </div>
    <div class="banner-three-items__item">
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner-three-items-block-2')->toHtml(); ?>
    </div>
    <div class="banner-three-items__item">
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner-three-items-block-3')->toHtml(); ?>
    </div>
    <div class="banner-three-items__item">
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner-image-video-block-1')->toHtml(); ?>
    </div>
    <div class="banner-three-items__item">
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner-image-video-block-2')->toHtml(); ?>
    </div>
</div>