<div class="main-banner-two-items">
    <div class="main-banner-two-items__item">
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('main-banner-two-items-1')->toHtml(); ?>
    </div>
    <div class="main-banner-two-items__item">
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('main-banner-two-items-2')->toHtml(); ?>
    </div>
</div>