<div class="review-service">
    <div class="review-service__title">
        <h2>Outdoor elegance testimonials</h2>
    </div>
    <div class="list-review-service">
        <div class="review-service__item">
            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('review-service-1')->toHtml(); ?>
        </div>
        <div class="review-service__item">
            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('review-service-2')->toHtml(); ?>
        </div>
        <div class="review-service__item">
            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('review-service-3')->toHtml(); ?>
        </div>
        <div class="review-service__item">
            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('review-service-4')->toHtml(); ?>
        </div>
    </div> 
    <button class="btn-view-more-testi">View more testimonials</button> 
</div>